version: "2"
services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2023
      - POSTGRES_DB=postgres
    restart: always # run as a service
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  dbadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "salhany805@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "maher2003"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always # run as a service

  odoo17:
    container_name: odoo17
    image: odoo:17
    user: root
    depends_on:
      - db
    ports:
      - "10017:8069"
      - "20017:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo17@2023
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always

volumes:
  pgadmin_data:
